#ifndef KOCSI_H
#define KOCSI_H
#include <string>

#include "Ules.h"
enum eKocsiTipus
{
    Elso,
    Masod,
    Alvo
};
class Kocsi
{
private:
    Kocsi *nextNode = nullptr;
    int KocsiSzam;
    eKocsiTipus KocsiTipus;
    Ules **UlesArray;

public:
    Kocsi(const int cKocsiSzam = -1, eKocsiTipus cKocsiTipus = Elso); // The Ules array will be generated by the constructor according to the type of the car and the number of a car. Each passanger car will have fix 60 seats. So the array containing the Ules-classes will be 60 long and the seat numbers will change according to the car number. E.g car 1: 1-60 (seat num), car 2 : 60-120 (seat num).Sleaping cars will have 60 beds.
    Kocsi(Kocsi* KocsiCopy);
    ~Kocsi();
    int getKocsiSzam();
    eKocsiTipus getKocsiTipus();
    Ules* FindUlesBySzam(int UlesSzam);
    static eKocsiTipus stringToKocsiTipus(const std::string KocsiTipus);
    Kocsi *getNextNode();
    void setNextNode(Kocsi *nextPtr);
    void operator+(Kocsi *newKocsi);
};

#endif